#!/usr/bin/with-contenv sh

#set -x

source /etc/colors.sh

PREFFIX="[services.d] [sshfs]-$(s6-basename ${0}):"

SERVICE_DIR=/var/run/s6/services
SERVICE=sshfs

checkSshfs(){
#    pgrep sshfs > /dev/null
    ps aux | grep '.sshfs.*'$RemotePath'' | grep -v grep > /dev/null
    return $?
}

#s6-echo "shutdown sshfs mount[DEBUG]"
if checkSshfs; then
    s6-svc -d ${SERVICE_DIR}/${SERVICE}
#    s6-svc -t ${SERVICE_DIR}/${SERVICE}
    tempPID="$(pgrep sshfs)"
    kill ${tempPID}
else
    echo -e "${PREFFIX} ${Red}sshfs process not present, restarting container[ERROR]${Color_Off}"
    s6-svscanctl -t /var/run/s6/services
fi

echo -e "${PREFFIX} ${Yellow}waiting for sshfs shutdown${Color_Off}"
while checkSshfs -eq 0; do
    sleep 0.1
done


#bring container down when sshfs crashes
#s6-svscanctl -t /var/run/s6/services

#while $(pgrep sshfs > /dev/null); do
#    sleep 0.1
#done

#s6-svc -wD /var/run/s6/services/sshfs/

#if ps aux | grep 's6-supervise sshfs' | grep -v grep > /dev/null; then s6-svc -t /var/run/s6/services/sshfs; fi;
